### ISSUE TITLE
Erro: `groupadd: GID '20' already exists`

### ISSUE THREAD

**Issue by HenriqueSilverio** [juliohm1978/dockerbb#1]
Ao rodar o `make start` me dá o seguinte erro:

```bash
+ groupadd -g 20 user
groupadd: GID '20' already exists
make: *** [start] Error 4
```

- **OS:** macOS Mojave 10.14.15
- **Docker:** 2.0.0.3

**Comment by juliohm1978** [comment]
Poderia enviar mais linhas da execução?

Parece que o container não está sendo recriado na hora de executar o `make start`. Confira se já não existe um container com este nome.

```bash
docker ps -a | grep dockerbb
```

Se houver, remova e tente novamente.

```bash
docker rm dockerbb
```

**Comment by HenriqueSilverio** [comment]
Fala @juliohm1978, beleza? 

Então cara, antes de rodar o `make start`, eu zerei tudo com um `docker system prune -a`.

Segue o output completo ao rodar o `make start`:

```bash
$ make start
echo /Users/rike/.Xauthority
/Users/rike/.Xauthority
exit
docker stop dockerbb
Error response from daemon: No such container: dockerbb
make: [start] Error 1 (ignored)
docker rm -f dockerbb
Error: No such container: dockerbb
make: [start] Error 1 (ignored)
docker run -it --rm --name dockerbb \
		-e USER_UID=501 \
		-e USER_GID=20 \
		--shm-size 100m \
		--net host \
		--hostname MacBook-Pro-de-Henrique.local \
		-e XSOCK \
		-e XAUTH \
		-e DISPLAY \
		-v "/Users/rike/.Xauthority:/home/user/.Xauthority:rw" \
		--cap-add SYS_ADMIN \
		-v "/Users/rike/dockerbb-data:/home/user" \
		dockerbb www.bb.com.br
+ groupadd -g 20 user
groupadd: GID '20' already exists
make: *** [start] Error 4
```

**Comment by juliohm1978** [comment]
Ah, entendo... O gid 20 já existe dentro do container.

```
root@573fb6a0bc6d:/# cat /etc/group | grep 20
dialout:x:20:
```

Deve ser algum grupo de sistema padrão do linux. Até onde vejo na Internet, o gid 20 é uma coisa padrão de algumas instalações do macOS.

Acredito que vc pode tentar deixar o gid com valor 1000. O seu user id pode continuar 501, que não existe dentro do container. Os arquivos no volume ficarão gravados com uid:gid 501:1000, mas isso provavelmente não será problema para o seu usuário ler e escrever no diretório de volume.

**Comment by HenriqueSilverio** [comment]
No arquivo `Makefile`, linha 2, coloquei `USER_GID = 1000`. É isso mesmo? 🤔 

Aí refiz o processo do zero: `docker system prune -a`... `make`... `make start`.

Dessa vez o output mudou, parece ter "avançado" um pouco, mas deu outro erro...

```
$ make start
echo /Users/rike/.Xauthority
/Users/rike/.Xauthority
exit
docker stop dockerbb
Error response from daemon: No such container: dockerbb
make: [start] Error 1 (ignored)
docker rm -f dockerbb
Error: No such container: dockerbb
make: [start] Error 1 (ignored)
docker run -it --rm --name dockerbb \
		-e USER_UID=501 \
		-e USER_GID=1000 \
		--shm-size 100m \
		--net host \
		--hostname MacBook-Pro-de-Henrique.local \
		-e XSOCK \
		-e XAUTH \
		-e DISPLAY \
		-v "/Users/rike/.Xauthority:/home/user/.Xauthority:rw" \
		--cap-add SYS_ADMIN \
		-v "/Users/rike/dockerbb-data:/home/user" \
		dockerbb www.bb.com.br
+ groupadd -g 1000 user
+ useradd -u 501 -g 1000 -ms /bin/bash user
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
+ dpkg -i /w.deb
Selecting previously unselected package warsaw.
(Reading database ... 28020 files and directories currently installed.)
Preparing to unpack /w.deb ...
Unpacking warsaw (1.13.1-2) ...
Setting up warsaw (1.13.1-2) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
+ rm -fr /w.deb
+ /usr/local/bin/warsaw/core
+ sleep 10
+ chown -R user.user /home/user
+ gosu user:user /usr/local/bin/warsaw/core
+ gosu user:user google-chrome www.bb.com.br
[73:73:0612/144516.303273:ERROR:browser_dm_token_storage_linux.cc(101)] Error: /etc/machine-id contains 0 characters (32 were expected).

(google-chrome:73): Gtk-WARNING **: 14:45:16.691: cannot open display: /private/tmp/com.apple.launchd.GLb1IA7rJx/org.macosforge.xquartz:0
make: *** [start] Error 1
```
Eu tenho o [XQuartz](https://www.xquartz.org/), só não sei se precisa configurar algo a mais...

**Comment by juliohm1978** [comment]
Vix rapaz... realmente manjo pouco sobre do gerenciador de janelas.. especialmente do macOS.

O container precisa usar o ambiente X do host para mostrar a janela do navegador. As variáveis XSOCK, XAUTH e DISPLAY dizem respeito ao ambiente X padrão no Ubuntu. Não sei dizer como seria essa relação com o XQuartz, por exemplo.

Já tentou executar com modo privilegiado? Ao invés do `--cap-add SYS_ADMIN`, troque por incluir `--privileged` e veja se funciona com permissões completas no container.

**Comment by juliohm1978** [comment]
Confira esse link
https://gist.github.com/cschiewek/246a244ba23da8b9f0e7b11a68bf3285

Talvez ajude

**Comment by juliohm1978** [comment]
@HenriqueSilverio ,

Se tiver interesse, pode testar a versão 2.0 que não precisa do X11 do host onde o container executa. Acabei de preparar esta versão que tem o Xfce e VNC dentro do container e vc pode acessar pelo seu navegador do host.

http://localhost:6080/vnc_auto.html

**Comment by HenriqueSilverio** [comment]
Resolvido. Na `v3.1` funcionou aqui sem precisar alterar nada. Obrigado!
