### ISSUE TITLE
Problem with chromium version 

### ISSUE THREAD

**Issue by patonoide** [juliohm1978/dockerbb#10]
When trying to build the container there is an error related to the chromium version. 

`chromium-browser : Depends: chromium-codecs-ffmpeg-extra (= 91.0.4472.101-0ubuntu0.18.04.1) but 92.0.4515.107-0ubuntu0.18.04.1 is to be installed or chromium-codecs-ffmpeg (= 91.0.4472.101-0ubuntu0.18.04.1) but it is not going to be installed Recommends: chromium-browser-l10n but it is not going to be installed`

Updating the version to 92 on the Dockerfile solves it.

**Comment by juliohm1978** [comment]
Fixed with new release https://github.com/juliohm1978/dockerbb/releases/tag/v3.7
