### ISSUE TITLE
Quais bancos

### ISSUE THREAD

**Issue by marcelokrol** [juliohm1978/dockerbb#12]
Estou adquirindo uma maquina nova, e pensei em usar docker para isolar esse acesso aos bancos, e em uma rápida pesquisa no google apareceu seu repositório.
Duvidas:
- No título você comenta o BB, já testou com outros bancos? 
- É fácil integrar com outros bancos e talvez colaborar com o projeto?

Excelente iniciativa, parabéns

**Comment by juliohm1978** [comment]
Olá.

Não funciona com todos os bancos. Acredito que o Itaú usa o mesmo warsaw, mas não tenho certeza. Meu teste aqui é só com o BB, infelizmente.
