### ISSUE TITLE
Version '95*' for 'chromium-browser' was not found

### ISSUE THREAD

**Issue by juliahno** [juliohm1978/dockerbb#13]
Não consigo instalar a versão 95, que está setada no repositório.

Tentei instalar a versão 102 do "chromium", mas também não funciona. 
Neste último caso, o erro é "Error response from daemon: can not get logs from container which is dead or marked for removal"

Obrigado!

`The command '/bin/sh -c apt-get update && apt-get install -y     libnss3-tools     zenity     libgtk2.0-0     dbus-x11     yad     libcurl3     libdbus-1.3     sudo gosu     libxss1     lsb-release     wget     xdg-utils     net-tools     openssl=${OPENSSL_VERSION}*     xfce4=${XFCE_VERSION}*     xfwm4=${XFWM4_VERSION}*     x11vnc=${X11VNC_VERSION}*     xvfb=${XVFB_VERSION}*     novnc=${NOVNC_VERSION}*     chromium-browser=${CHROME_VERSION}*     && dpkg -l | awk '{print "|" $2 "|" $3 "|"}' > /installed-packages.txt' returned a non-zero code: 100
make: *** [Makefile:14: build] Error 100`

**Comment by juliohm1978** [comment]
Acabei de atualizar o Dockerfile. Poderia fazer um git pull e tentar novamente?

**Comment by juliahno** [comment]
Boa tarde, Julio. O erro persiste pra versão 101 do chromium.
```
Error response from daemon: can not get logs from container which is dead or marked for removal
make: *** [Makefile:26: start] Error 1
```
Obrigado!

**Comment by juliahno** [comment]
Agora foi. Obrigado!
