### ISSUE TITLE
Crash no X do host

### ISSUE THREAD

**Issue by hsantanna** [juliohm1978/dockerbb#5]
Quando fiz um `make start` na primeira vez após o build o servidor xorg do meu host morreu.
Fiz login novamente e repeti o `make start`, então nessa segunda vez o container subiu ok e pude acessar o VNC no meu navegador.

Estou no Arch Linux,
- kernel LTS (5.4.72-1-lts)
- xorg-server (1.20.9-2)

Farei novos testes e relatarei aqui o resultado.

**Comment by juliohm1978** [comment]
Pois é... acredito que pode ser algum conflito com o `/sbin/init` e o fato de que o container está rodando em modo privilegiado. Já vi isso acontecer em outro notebook também.

No meu desktop, parece que o kernel tem algumas reações estranhas quando outro `/sbin/init` executa, mesmo dentro do container. Popups aparecem como seu eu tivesse ajustado o volume.

Seria bom poder rodar o `/sbin/init` em modo de usuário comum. Mas ainda não consegui fazer isso.

**Comment by juliohm1978** [comment]
Sem retorno e sem perspective de diagnóstico. Precisando, pode ser reaberto.
