### ISSUE TITLE
Site do BB não identifica o módulo de segurança

### ISSUE THREAD

**Issue by diraol** [juliohm1978/dockerbb#6]
Não sei se está acontecendo com vocês também, mas para mim o site do BB não está conseguindo identificar o módulo de segurança. Testei a solução aqui proposta (`dockerbb`), testei numa VM com Windows (que eu sempre usei para isso), testei num computador com Windows full install .... nada...

**Comment by juliohm1978** [comment]
Difícil dizer. Esse módulo é uma caixa preta. Não existe log, não existe output em lugar algum.

Mas, no caso, se não funciona nem no Windows, pode ser outra coisa externa. Algum firewall ou antivírus? Tente desligar temporariamente para ver se faz diferença.

**Comment by diraol** [comment]
Estranho, voltou a funcionar (tanto na VM windows quanto no Windows instalado em outra máquina), mas não no dockerbb.... vai entender.
Amanhã testo de novo, pode ter sido algum problema transiente.
