### ISSUE TITLE
[Dúvida] Docker + Warsaw + Puppeteer

### ISSUE THREAD

**Issue by HenriqueSilverio** [juliohm1978/dockerbb#7]
Olá, tudo bom?

Preciso rodar um script [Puppeteer](https://pptr.dev/#?product=Puppeteer&version=v3.3.0) com o Warsaw instalado.

Já tentei adaptar de diversas maneiras aqui mas nada deu certo ainda.

Alguém teria alguma luz sobre como fazer? 

Desde já grato pela atenção.

**Comment by juliohm1978** [comment]
Oi Henrique.

Não tenho experiência com o Puppeteer. Poderia dar mais detalhes do seu ambiente e do erro que ocorre? Trata-se da imagem Docker deste projeto? Ou uma imagem sua com outro Dockerfile?

No console de debug do navegador, podem aparecer algumas mensagens de erro indicando que não foi possível se conectar a 127.0.0.1 e isso gera a mensagem de que o módulo de segurança não foi encontrado.

Até onde sei, ele precisa de duas instâncias do binário `core`, uma executando como root e outra com o UID do usuário que navega. Além do site do banco, o navegador se conecta via websocket em http://127.0.0.1 na porta do warsaw para trocar informações sigilosas com o banco.

Fora isso, não sei muito mais como resolver problemas inerentes ao Warsaw. Ele é um software muito bem fechado. Um blackbox que parece não imprimir nada em lugar algum para não dar dicas do que está fazendo. A versão mais recente, por exemplo, nem pode ser instalada sem a presença do `/sbin/init` instanciado com PID 1. Dentro de um container, isso só é possível hoje com modo privilegiado (`docker run --privileged`)

**Comment by HenriqueSilverio** [comment]
Oi @juliohm1978!

Primeiramente peço desculpas pela **grande** demora em responder aqui.

E voltando ao assunto... bom, resumindo... consegui resolver! 🎉 

Criei um "fork" do seu repositório: https://github.com/HenriqueSilverio/docker-warsaw-puppeteer.

Muito obrigado pela ajuda! 👊 😄

**Comment by juliohm1978** [comment]
Jóia!

Com algumas experiências aqui, consegui executar o dockerbb com o [Podman](https://podman.io/). O container ainda precisa rodar em modo privilegiado, mas como é iniciado por um usuário comum (ao invés do root com Docker) o **_/sbin/init_** se comporta melhor isolado.
