### ISSUE TITLE
E: Version '89*' for 'chromium-browser' was not found

### ISSUE THREAD

**Issue by douglas-melo** [juliohm1978/dockerbb#8]
Fala Julio, tudo certo? Primeiramente, muito obrigado por disponibilizar a imagem!

Tentei fazer o build, e recebi ```E: Version '89*' for 'chromium-browser' was not found```. Ao que parece esta versão do chromium não está mais disponível para ```ubuntu:18.04```.  Não fiz mais nenhum teste.

Segue mensagem completa: 

```
E: Version '89*' for 'chromium-browser' was not found 
The command '/bin/sh -c apt-get update && apt-get install -y     libnss3-tools     zenity     libgtk2.0-0     dbus-x11     yad     libcurl3     libdbus-1.3     sudo gosu     libxss1     lsb-release     wget     xdg-utils     net-tools     openssl=${OPENSSL_VERSION}*     xfce4=${XFCE_VERSION}*     xfwm4=${XFWM4_VERSION}*     x11vnc=${X11VNC_VERSION}*     xvfb=${XVFB_VERSION}*     novnc=${NOVNC_VERSION}*     chromium-browser=${CHROME_VERSION}*     && dpkg -l | awk '{print "|" $2 "|" $3 "|"}' > /installed-packages.txt' returned a non-zero code: 100
make: *** [Makefile:14: build] Error 10
```
Valeu!!!

**Comment by juliohm1978** [comment]
Oi Douglas.

Acho que o Dockerfile precisa de uma atualização. O repositório já deve não ter mais a versão 89.

Tente alterar o Dockerfile para usar a versão 90, ou a que for mais recente.

**Comment by douglas-melo** [comment]
Sim Julio, obrigado. 

Eu havia testado com versão 90 também e não tinha funcionado, alterei o DockerFile para a versão 91 e funcionou.
Tomei a liberdade de criar um pull request.

Abraço!

**Comment by juliohm1978** [comment]
Resolvido com a PR https://github.com/juliohm1978/dockerbb/pull/9
